"""Canonical, point-in-time data foundation for the research product."""

from .contracts import (
    CONTRACT_VERSION,
    RECORD_SCHEMAS,
    Provenance,
    RawCapture,
    RecordDomain,
    RecordEnvelope,
    RecordSchema,
    RecordStatus,
    SourceManifest,
    contract_descriptor,
    validate_adapter_output,
)
from .authority_sink import AuthoritySinkError, ObjectStore, SupabaseAuthoritySink
from .disclosed_scoring import (
    COMPOSITE_WEIGHTS,
    OPPORTUNITY_WEIGHTS,
    QUANTIFIABLE_WEIGHT,
    composite_score,
    opportunity_score,
    peg_grade,
)
from .ashare import (
    AShareDataGap,
    AShareDataPacket,
    AShareInstrument,
    AShareTickerError,
    EASTMONEY_BALANCE_SOURCE,
    EASTMONEY_CASHFLOW_SOURCE,
    EASTMONEY_FUNDAMENTAL_SOURCE,
    EASTMONEY_INCOME_SOURCE,
    EastmoneyFundamentalAdapter,
    EastmoneyStatementAdapter,
    MemoryAuthoritySink,
    TENCENT_KLINE_SOURCE,
    TENCENT_QUOTE_SOURCE,
    TencentDailyBarAdapter,
    TencentQuoteAdapter,
    build_ashare_registry,
    build_ashare_runtime,
    collect_ashare_packet,
    collect_ashare_packet_async,
    normalize_ashare_ticker,
)
from .eastmoney_periodic import (
    EASTMONEY_BUSINESS_COMPOSITION_SOURCE,
    EASTMONEY_EARNINGS_CALENDAR_SOURCE,
    EastmoneyBusinessCompositionAdapter,
    EastmoneyEarningsCalendarAdapter,
    EastmoneyPeriodicPayloadError,
    EarningsCalendarCollection,
    MemoryAttemptSink,
    build_eastmoney_periodic_registry,
    build_eastmoney_periodic_runtime,
    collect_eastmoney_earnings_calendar,
    collect_eastmoney_earnings_calendar_async,
)
from .market_snapshot import (
    HISTORICAL_MARKET_FIELD_POLICY,
    MARKET_FIELD_SOURCES,
    SEC_COMPANY_FACTS_SOURCE,
    YAHOO_CHART_SOURCE,
    YAHOO_FX_SOURCE,
    YAHOO_SNAPSHOT_SOURCE,
    GlobalInstrument,
    SecCompanyFactsAdapter,
    YahooChartAdapter,
    YahooFxAdapter,
    YahooSnapshotAdapter,
    compare_snapshot,
    derive_historical_valuation,
    normalize_global_ticker,
    sec_point_in_time_inputs,
)
from .market_regime_data import (
    COMMERCIAL_RIGHTS_APPROVED,
    DISABLED,
    INSTRUMENTS,
    INSTRUMENT_BY_KEY,
    LOCAL_EVALUATION,
    LicenseDecision,
    LicenseGateError,
    MarketRegimeDataError,
    MarketRegimeDataStore,
    SourceCaptureError,
    instrument_registry_payload,
    license_decision,
    normalize_capture,
)
from .ingestion import (
    AdapterContractError,
    AdapterRegistry,
    AuthoritySink,
    BatchQuality,
    FetchedPayload,
    FetchCache,
    FetchRequest,
    IngestionAttempt,
    IngestionOutcome,
    IngestionRuntime,
    QualityPolicy,
    SourceAdapter,
    SourceChoice,
    ValidatedFetch,
    build_raw_capture,
    evaluate_records,
    validate_fetched_payload,
)
from .ashare_validation import (
    AShareSecurityMasterEntry,
    AShareSourceConflict,
    AShareValidatedPacket,
    CNINFO_CORPORATE_ACTION_SOURCE,
    EASTMONEY_QUOTE_SOURCE,
    SINA_KLINE_SOURCE,
    CninfoCorporateActionAdapter,
    EastmoneyQuoteCrosscheckAdapter,
    SinaDailyBarCrosscheckAdapter,
    build_validation_runtime,
    collect_validated_ashare_packet,
    collect_validated_ashare_packet_async,
)
from .local_cache import CachedReportTask, SQLiteFetchCache, SQLiteReportTaskCache
from .report_task_runtime import (
    REPORT_TASK_RUNTIME_VERSION,
    ReportTask,
    ReportTaskResult,
    run_report_task_batch,
)
from .research_degradation import (
    DEGRADATION_POLICY_VERSION,
    DegradationReceipt,
    ResearchTier,
    SourceGapAction,
    assess_any_ticker,
)
from .research_refresh import (
    CanonicalComponent,
    CanonicalResearchRefresh,
    CanonicalPublicationError,
    canonical_active_report,
    canonical_active_summary,
    CollectedBundle,
    FileBundleFallbackAdapter,
    InjectedInterruption,
    LegacyCollectorAdapter,
    RefreshInProgressError,
)
from .store import DataFoundation, QualityGateError, SnapshotReader
from .research_objects import (
    ALLOWED_CONFIDENCE,
    ALLOWED_STATES,
    OBJECT_SCHEMAS,
    RESEARCH_OBJECT_SCHEMA_VERSION,
    ResearchObject,
    ResearchObjectSchema,
    ResearchObjectStore,
    ResearchObjectType,
    object_contract_descriptor,
)
from .research_object_publish import ResearchObjectPublishError, ResearchObjectPublisher
from .research_object_read import CanonicalReadError, CanonicalResearchReader
from .snapshot_orchestration import (
    CanonicalGap,
    ORCHESTRATION_SCHEMA_VERSION,
    RefreshPlan,
    SnapshotOrchestrator,
    build_refresh_plan,
    detect_canonical_gaps,
    snapshot_audit,
)
from .official_filings import (
    BSE_FILING_DOCUMENT_SOURCE,
    CNINFO_FILING_DOCUMENT_SOURCE,
    CNINFO_FILING_INDEX_SOURCE,
    SSE_FILING_INDEX_SOURCE,
    SSE_FILING_DOCUMENT_SOURCE,
    SZSE_FILING_DOCUMENT_SOURCE,
    CninfoFilingIndexAdapter,
    SseFilingIndexAdapter,
    HttpResponse,
    OfficialFilingBatch,
    OfficialFilingDocumentAdapter,
    build_official_filing_registry,
    build_official_filing_runtime,
    classify_filing_title,
    sync_cninfo_filings,
    sync_cninfo_filings_async,
    sync_exchange_filings,
    sync_exchange_filings_async,
    sync_sse_filings,
    sync_sse_filings_async,
    validate_official_source_role,
)
from .industry_ontology import (
    ONTOLOGY_VERSION,
    IndustryNode,
    IndustrySegment,
    build_ontology,
    ontology_receipt,
    validate_ontology,
)
from .industry_company_index import (
    INDUSTRY_COMPANY_INDEX_SCHEMA_VERSION,
    IndustryCompanyIndex,
    build_industry_company_index,
)
from .n3_dossier_batch import (
    N3_DOSSIER_BATCH_SCHEMA_VERSION,
    N3_DOSSIER_BATCH_SIZE,
    compile_batch as compile_n3_dossier_batch,
    selected_positions as n3_dossier_batch_positions,
)
from .r2_acceptance import R2_ACCEPTANCE_SCHEMA_VERSION, audit_r2
from .n3_financial_delivery import N3_FINANCIAL_DELIVERY_SCHEMA_VERSION, run_financial_delivery_batch
from .document_intelligence import (
    DEFAULT_PARSER_VERSION,
    CitationCheck,
    CitationReturnPath,
    CorpusQuality,
    DocumentChunk,
    DocumentPage,
    DocumentParseResult,
    PageCitation,
    ParserConfig,
    PublicationGateResult,
    ReportClaim,
    TesseractCliOCR,
    assess_corpus_quality,
    parse_pdf_document,
    resolve_citation_return_path,
    validate_publication_citations,
)
from .vertical_slices import (
    OFFICIAL_EVIDENCE_ANCHORS,
    VERTICAL_SLICE_AS_OF,
    VerticalSliceReceipt,
    compile_three_company_vertical_slices,
    compile_vertical_slice,
    official_evidence_anchors,
    vertical_slice_audit,
)
from .consensus_history import (
    CONSENSUS_SCHEMA_VERSION,
    THS_FORECAST_SOURCE,
    BrokerEstimate,
    ConsensusPoint,
    ConsensusRevision,
    ConsensusSnapshot,
    EstimateQuarantine,
    ProviderConsensusReference,
    ThsForecastAdapter,
    build_consensus_snapshot,
    build_ths_forecast_runtime,
    compare_consensus_snapshots,
    estimates_from_catalog_outcomes,
    normalize_broker_estimate,
    reconcile_ths_broker_estimates,
    ths_consensus_references,
)
from .event_intelligence import (
    INTELLIGENCE_SCHEMA_VERSION,
    SUPPORTED_SOURCE_TYPES,
    AShareEntityResolver,
    CoverageGap,
    EntityResolution,
    InferenceEnvelope,
    IntelCollectorAdapter,
    IntelSourceSpec,
    IntelligenceBatch,
    IntelligenceEvent,
    IntelligenceEvidence,
    attach_event_inference,
    build_event_topology,
    canonical_article_url,
    collect_intelligence,
    collect_intelligence_async,
)
from .research_outcomes import OUTCOME_SCHEMA_VERSION, build_outcome_receipt
from .evidence_gate import (
    EVIDENCE_GATE_SCHEMA_VERSION,
    CoverageReport,
    CoverageRequirementResult,
    EvidenceCandidate,
    EvidenceConflict,
    EvidenceGatePolicy,
    EvidenceGateReceipt,
    EvidenceRequirement,
    EvidenceRole,
    ImmutableEvidenceSet,
    RejectedEvidence,
    ResearchContextPack,
    SourceCoverageGap,
    build_context_pack,
    build_evidence_set,
    verify_evidence_set,
)
from .sell_side_archive import (
    EASTMONEY_SELL_SIDE_CATALOG_SOURCE,
    EASTMONEY_SELL_SIDE_PDF_SOURCE,
    EastmoneySellSideCatalogAdapter,
    EastmoneySellSidePdfAdapter,
    RateLimitedRetryTransport,
    RetryableHttpError,
    SellSideArchiveBatch,
    SellSideArchiveItem,
    build_sell_side_runtime,
    sync_sell_side_archive,
    sync_sell_side_archive_async,
)
from .storage_layout import RAW_BUCKET, StorageObjectKey, raw_storage_key
from .viewpoint_matrix import (
    VIEWPOINT_MATRIX_SCHEMA_VERSION,
    BlockedViewpointClaim,
    SellSideViewpoint,
    SellSideViewpointMatrix,
    TopicEvidence,
    ViewpointClaim,
    ViewpointCoverage,
    ViewpointRevision,
    ViewpointRow,
    build_sell_side_viewpoint_matrix,
)
from .valuation_context import (
    VALUATION_CONTEXT_SCHEMA_VERSION,
    ContextBoundValuation,
    ViewpointContextReceipt,
    run_context_bound_valuation,
    validate_viewpoint_matrix_context,
)
from .industry_catalysts import (
    CATALYST_PROFILE_SCHEMA_VERSION,
    CatalystSection,
    IndustryCatalystProfile,
    build_catalyst_profiles,
    catalyst_coverage,
)
from .dossier_generator import (
    DOSSIER_SCHEMA_VERSION,
    CompanyDossier,
    DossierSection,
    compile_dossier,
)
from .decision_policy import DecisionInput, DecisionReceipt, POLICY_VERSION, decide
from .offline_report_model import OfflineReportModel, compile_offline_report_model
from .sector_taxonomy import SECTOR_TAXONOMY_VERSION, SectorSegment, build_cross_sector_taxonomy, taxonomy_receipt, validate_position_segment

__all__ = [
    "CanonicalComponent", "CanonicalPublicationError", "CanonicalResearchRefresh",
    "canonical_active_report", "canonical_active_summary",
    "CollectedBundle", "DataFoundation", "InjectedInterruption",
    "FileBundleFallbackAdapter", "LegacyCollectorAdapter", "QualityGateError", "RefreshInProgressError", "SnapshotReader",
    "CONTRACT_VERSION", "RECORD_SCHEMAS", "Provenance", "RawCapture",
    "RecordDomain", "RecordEnvelope", "RecordSchema", "RecordStatus",
    "SourceManifest", "contract_descriptor", "validate_adapter_output",
    "COMMERCIAL_RIGHTS_APPROVED", "DISABLED", "INSTRUMENTS", "INSTRUMENT_BY_KEY",
    "LOCAL_EVALUATION", "LicenseDecision", "LicenseGateError", "MarketRegimeDataError",
    "MarketRegimeDataStore", "SourceCaptureError", "instrument_registry_payload",
    "license_decision", "normalize_capture",
    "RAW_BUCKET", "StorageObjectKey", "raw_storage_key",
    "AdapterContractError", "AdapterRegistry", "AuthoritySink", "AuthoritySinkError",
    "BatchQuality", "FetchedPayload", "FetchCache", "FetchRequest", "IngestionAttempt",
    "IngestionOutcome", "IngestionRuntime", "ObjectStore", "QualityPolicy", "SourceAdapter",
    "SourceChoice", "SQLiteFetchCache", "SupabaseAuthoritySink", "ValidatedFetch",
    "build_raw_capture", "evaluate_records", "validate_fetched_payload",
    "AShareDataGap", "AShareDataPacket", "AShareInstrument", "AShareTickerError",
    "EASTMONEY_BALANCE_SOURCE", "EASTMONEY_CASHFLOW_SOURCE",
    "EASTMONEY_FUNDAMENTAL_SOURCE", "EASTMONEY_INCOME_SOURCE",
    "EastmoneyFundamentalAdapter", "EastmoneyStatementAdapter", "MemoryAuthoritySink",
    "TENCENT_KLINE_SOURCE", "TENCENT_QUOTE_SOURCE", "TencentDailyBarAdapter",
    "TencentQuoteAdapter", "build_ashare_registry", "build_ashare_runtime",
    "collect_ashare_packet", "collect_ashare_packet_async", "normalize_ashare_ticker",
    "AShareSecurityMasterEntry", "AShareSourceConflict", "AShareValidatedPacket",
    "CNINFO_CORPORATE_ACTION_SOURCE", "EASTMONEY_QUOTE_SOURCE", "SINA_KLINE_SOURCE",
    "CninfoCorporateActionAdapter", "EastmoneyQuoteCrosscheckAdapter",
    "SinaDailyBarCrosscheckAdapter", "build_validation_runtime",
    "collect_validated_ashare_packet", "collect_validated_ashare_packet_async",
    "CanonicalGap", "ORCHESTRATION_SCHEMA_VERSION", "RefreshPlan",
    "SnapshotOrchestrator", "build_refresh_plan", "detect_canonical_gaps",
    "snapshot_audit",
    "BSE_FILING_DOCUMENT_SOURCE", "CNINFO_FILING_DOCUMENT_SOURCE",
    "CNINFO_FILING_INDEX_SOURCE", "SSE_FILING_INDEX_SOURCE", "SSE_FILING_DOCUMENT_SOURCE",
    "SZSE_FILING_DOCUMENT_SOURCE", "CninfoFilingIndexAdapter", "HttpResponse",
    "OfficialFilingBatch", "OfficialFilingDocumentAdapter", "SseFilingIndexAdapter",
    "build_official_filing_registry", "build_official_filing_runtime",
    "classify_filing_title", "sync_cninfo_filings", "sync_cninfo_filings_async",
    "sync_exchange_filings", "sync_exchange_filings_async", "sync_sse_filings",
    "sync_sse_filings_async",
    "validate_official_source_role",
    "ONTOLOGY_VERSION", "IndustryNode", "IndustrySegment", "build_ontology", "ontology_receipt", "validate_ontology",
    "INDUSTRY_COMPANY_INDEX_SCHEMA_VERSION", "IndustryCompanyIndex", "build_industry_company_index",
    "N3_DOSSIER_BATCH_SCHEMA_VERSION", "N3_DOSSIER_BATCH_SIZE", "compile_n3_dossier_batch", "n3_dossier_batch_positions",
    "R2_ACCEPTANCE_SCHEMA_VERSION", "audit_r2",
    "N3_FINANCIAL_DELIVERY_SCHEMA_VERSION", "run_financial_delivery_batch",
    "DEFAULT_PARSER_VERSION", "CitationCheck", "CitationReturnPath", "CorpusQuality", "DocumentChunk",
    "CachedReportTask", "SQLiteReportTaskCache", "REPORT_TASK_RUNTIME_VERSION", "ReportTask",
    "ReportTaskResult", "run_report_task_batch",
    "DEGRADATION_POLICY_VERSION", "DegradationReceipt", "ResearchTier", "SourceGapAction",
    "assess_any_ticker",
    "DocumentPage", "DocumentParseResult", "PageCitation", "ParserConfig",
    "PublicationGateResult", "ReportClaim", "TesseractCliOCR",
    "OFFICIAL_EVIDENCE_ANCHORS", "VERTICAL_SLICE_AS_OF", "VerticalSliceReceipt",
    "compile_three_company_vertical_slices", "compile_vertical_slice", "official_evidence_anchors",
    "vertical_slice_audit",
    "assess_corpus_quality", "parse_pdf_document", "resolve_citation_return_path", "validate_publication_citations",
    "CONSENSUS_SCHEMA_VERSION", "BrokerEstimate", "ConsensusPoint",
    "ConsensusRevision", "ConsensusSnapshot", "EstimateQuarantine",
    "build_consensus_snapshot", "compare_consensus_snapshots",
    "estimates_from_catalog_outcomes", "normalize_broker_estimate",
    "THS_FORECAST_SOURCE", "ProviderConsensusReference", "ThsForecastAdapter",
    "build_ths_forecast_runtime", "reconcile_ths_broker_estimates",
    "ths_consensus_references",
    "INTELLIGENCE_SCHEMA_VERSION", "SUPPORTED_SOURCE_TYPES",
    "AShareEntityResolver", "CoverageGap", "EntityResolution",
    "InferenceEnvelope", "IntelCollectorAdapter", "IntelSourceSpec",
    "IntelligenceBatch", "IntelligenceEvent", "IntelligenceEvidence",
    "attach_event_inference", "build_event_topology", "canonical_article_url",
    "collect_intelligence", "collect_intelligence_async",
    "OUTCOME_SCHEMA_VERSION", "build_outcome_receipt",
    "EVIDENCE_GATE_SCHEMA_VERSION", "CoverageReport",
    "CoverageRequirementResult", "EvidenceCandidate", "EvidenceConflict",
    "EvidenceGatePolicy", "EvidenceGateReceipt", "EvidenceRequirement",
    "EvidenceRole", "ImmutableEvidenceSet", "RejectedEvidence",
    "ResearchContextPack", "SourceCoverageGap", "build_context_pack",
    "build_evidence_set", "verify_evidence_set",
    "EASTMONEY_SELL_SIDE_CATALOG_SOURCE", "EASTMONEY_SELL_SIDE_PDF_SOURCE",
    "EastmoneySellSideCatalogAdapter", "EastmoneySellSidePdfAdapter",
    "RateLimitedRetryTransport", "RetryableHttpError", "SellSideArchiveBatch",
    "SellSideArchiveItem", "build_sell_side_runtime", "sync_sell_side_archive",
    "sync_sell_side_archive_async",
    "VIEWPOINT_MATRIX_SCHEMA_VERSION", "BlockedViewpointClaim",
    "SellSideViewpoint", "SellSideViewpointMatrix", "TopicEvidence",
    "ViewpointClaim", "ViewpointCoverage", "ViewpointRevision", "ViewpointRow",
    "build_sell_side_viewpoint_matrix",
    "VALUATION_CONTEXT_SCHEMA_VERSION", "ContextBoundValuation", "ViewpointContextReceipt",
    "run_context_bound_valuation", "validate_viewpoint_matrix_context",
    "CATALYST_PROFILE_SCHEMA_VERSION", "CatalystSection", "IndustryCatalystProfile",
    "build_catalyst_profiles", "catalyst_coverage",
    "DOSSIER_SCHEMA_VERSION", "CompanyDossier", "DossierSection", "compile_dossier",
    "POLICY_VERSION", "DecisionInput", "DecisionReceipt", "decide",
    "OfflineReportModel", "compile_offline_report_model",
    "SECTOR_TAXONOMY_VERSION", "SectorSegment", "build_cross_sector_taxonomy", "taxonomy_receipt", "validate_position_segment",
]
