"""Canonical, point-in-time data foundation for the research product."""

from .contracts import (
    CONTRACT_VERSION,
    RECORD_SCHEMAS,
    Provenance,
    RawCapture,
    RecordDomain,
    RecordEnvelope,
    RecordSchema,
    RecordStatus,
    SourceManifest,
    contract_descriptor,
    validate_adapter_output,
)
from .authority_sink import AuthoritySinkError, ObjectStore, SupabaseAuthoritySink
from .ashare import (
    AShareDataGap,
    AShareDataPacket,
    AShareInstrument,
    AShareTickerError,
    EASTMONEY_BALANCE_SOURCE,
    EASTMONEY_CASHFLOW_SOURCE,
    EASTMONEY_FUNDAMENTAL_SOURCE,
    EASTMONEY_INCOME_SOURCE,
    EastmoneyFundamentalAdapter,
    EastmoneyStatementAdapter,
    MemoryAuthoritySink,
    TENCENT_KLINE_SOURCE,
    TENCENT_QUOTE_SOURCE,
    TencentDailyBarAdapter,
    TencentQuoteAdapter,
    build_ashare_registry,
    build_ashare_runtime,
    collect_ashare_packet,
    collect_ashare_packet_async,
    normalize_ashare_ticker,
)
from .ingestion import (
    AdapterContractError,
    AdapterRegistry,
    AuthoritySink,
    BatchQuality,
    FetchedPayload,
    FetchCache,
    FetchRequest,
    IngestionAttempt,
    IngestionOutcome,
    IngestionRuntime,
    QualityPolicy,
    SourceAdapter,
    SourceChoice,
    ValidatedFetch,
    build_raw_capture,
    evaluate_records,
    validate_fetched_payload,
)
from .ashare_validation import (
    AShareSecurityMasterEntry,
    AShareSourceConflict,
    AShareValidatedPacket,
    CNINFO_CORPORATE_ACTION_SOURCE,
    EASTMONEY_QUOTE_SOURCE,
    SINA_KLINE_SOURCE,
    CninfoCorporateActionAdapter,
    EastmoneyQuoteCrosscheckAdapter,
    SinaDailyBarCrosscheckAdapter,
    build_validation_runtime,
    collect_validated_ashare_packet,
    collect_validated_ashare_packet_async,
)
from .local_cache import SQLiteFetchCache
from .research_refresh import (
    CanonicalComponent,
    CanonicalResearchRefresh,
    CanonicalPublicationError,
    canonical_active_report,
    canonical_active_summary,
    CollectedBundle,
    FileBundleFallbackAdapter,
    InjectedInterruption,
    LegacyCollectorAdapter,
    RefreshInProgressError,
)
from .store import DataFoundation, QualityGateError, SnapshotReader
from .snapshot_orchestration import (
    CanonicalGap,
    ORCHESTRATION_SCHEMA_VERSION,
    RefreshPlan,
    SnapshotOrchestrator,
    build_refresh_plan,
    detect_canonical_gaps,
    snapshot_audit,
)
from .official_filings import (
    BSE_FILING_DOCUMENT_SOURCE,
    CNINFO_FILING_DOCUMENT_SOURCE,
    CNINFO_FILING_INDEX_SOURCE,
    SSE_FILING_DOCUMENT_SOURCE,
    SZSE_FILING_DOCUMENT_SOURCE,
    CninfoFilingIndexAdapter,
    HttpResponse,
    OfficialFilingBatch,
    OfficialFilingDocumentAdapter,
    build_official_filing_registry,
    build_official_filing_runtime,
    classify_filing_title,
    sync_cninfo_filings,
    sync_cninfo_filings_async,
    validate_official_source_role,
)
from .document_intelligence import (
    DEFAULT_PARSER_VERSION,
    CitationCheck,
    CorpusQuality,
    DocumentChunk,
    DocumentPage,
    DocumentParseResult,
    PageCitation,
    ParserConfig,
    PublicationGateResult,
    ReportClaim,
    TesseractCliOCR,
    assess_corpus_quality,
    parse_pdf_document,
    validate_publication_citations,
)
from .consensus_history import (
    CONSENSUS_SCHEMA_VERSION,
    THS_FORECAST_SOURCE,
    BrokerEstimate,
    ConsensusPoint,
    ConsensusRevision,
    ConsensusSnapshot,
    EstimateQuarantine,
    ProviderConsensusReference,
    ThsForecastAdapter,
    build_consensus_snapshot,
    build_ths_forecast_runtime,
    compare_consensus_snapshots,
    estimates_from_catalog_outcomes,
    normalize_broker_estimate,
    reconcile_ths_broker_estimates,
    ths_consensus_references,
)
from .event_intelligence import (
    INTELLIGENCE_SCHEMA_VERSION,
    SUPPORTED_SOURCE_TYPES,
    AShareEntityResolver,
    CoverageGap,
    EntityResolution,
    InferenceEnvelope,
    IntelCollectorAdapter,
    IntelSourceSpec,
    IntelligenceBatch,
    IntelligenceEvent,
    IntelligenceEvidence,
    attach_event_inference,
    build_event_topology,
    canonical_article_url,
    collect_intelligence,
    collect_intelligence_async,
)
from .sell_side_archive import (
    EASTMONEY_SELL_SIDE_CATALOG_SOURCE,
    EASTMONEY_SELL_SIDE_PDF_SOURCE,
    EastmoneySellSideCatalogAdapter,
    EastmoneySellSidePdfAdapter,
    RateLimitedRetryTransport,
    RetryableHttpError,
    SellSideArchiveBatch,
    SellSideArchiveItem,
    build_sell_side_runtime,
    sync_sell_side_archive,
    sync_sell_side_archive_async,
)
from .storage_layout import RAW_BUCKET, StorageObjectKey, raw_storage_key

__all__ = [
    "CanonicalComponent", "CanonicalPublicationError", "CanonicalResearchRefresh",
    "canonical_active_report", "canonical_active_summary",
    "CollectedBundle", "DataFoundation", "InjectedInterruption",
    "FileBundleFallbackAdapter", "LegacyCollectorAdapter", "QualityGateError", "RefreshInProgressError", "SnapshotReader",
    "CONTRACT_VERSION", "RECORD_SCHEMAS", "Provenance", "RawCapture",
    "RecordDomain", "RecordEnvelope", "RecordSchema", "RecordStatus",
    "SourceManifest", "contract_descriptor", "validate_adapter_output",
    "RAW_BUCKET", "StorageObjectKey", "raw_storage_key",
    "AdapterContractError", "AdapterRegistry", "AuthoritySink", "AuthoritySinkError",
    "BatchQuality", "FetchedPayload", "FetchCache", "FetchRequest", "IngestionAttempt",
    "IngestionOutcome", "IngestionRuntime", "ObjectStore", "QualityPolicy", "SourceAdapter",
    "SourceChoice", "SQLiteFetchCache", "SupabaseAuthoritySink", "ValidatedFetch",
    "build_raw_capture", "evaluate_records", "validate_fetched_payload",
    "AShareDataGap", "AShareDataPacket", "AShareInstrument", "AShareTickerError",
    "EASTMONEY_BALANCE_SOURCE", "EASTMONEY_CASHFLOW_SOURCE",
    "EASTMONEY_FUNDAMENTAL_SOURCE", "EASTMONEY_INCOME_SOURCE",
    "EastmoneyFundamentalAdapter", "EastmoneyStatementAdapter", "MemoryAuthoritySink",
    "TENCENT_KLINE_SOURCE", "TENCENT_QUOTE_SOURCE", "TencentDailyBarAdapter",
    "TencentQuoteAdapter", "build_ashare_registry", "build_ashare_runtime",
    "collect_ashare_packet", "collect_ashare_packet_async", "normalize_ashare_ticker",
    "AShareSecurityMasterEntry", "AShareSourceConflict", "AShareValidatedPacket",
    "CNINFO_CORPORATE_ACTION_SOURCE", "EASTMONEY_QUOTE_SOURCE", "SINA_KLINE_SOURCE",
    "CninfoCorporateActionAdapter", "EastmoneyQuoteCrosscheckAdapter",
    "SinaDailyBarCrosscheckAdapter", "build_validation_runtime",
    "collect_validated_ashare_packet", "collect_validated_ashare_packet_async",
    "CanonicalGap", "ORCHESTRATION_SCHEMA_VERSION", "RefreshPlan",
    "SnapshotOrchestrator", "build_refresh_plan", "detect_canonical_gaps",
    "snapshot_audit",
    "BSE_FILING_DOCUMENT_SOURCE", "CNINFO_FILING_DOCUMENT_SOURCE",
    "CNINFO_FILING_INDEX_SOURCE", "SSE_FILING_DOCUMENT_SOURCE",
    "SZSE_FILING_DOCUMENT_SOURCE", "CninfoFilingIndexAdapter", "HttpResponse",
    "OfficialFilingBatch", "OfficialFilingDocumentAdapter",
    "build_official_filing_registry", "build_official_filing_runtime",
    "classify_filing_title", "sync_cninfo_filings", "sync_cninfo_filings_async",
    "validate_official_source_role",
    "DEFAULT_PARSER_VERSION", "CitationCheck", "CorpusQuality", "DocumentChunk",
    "DocumentPage", "DocumentParseResult", "PageCitation", "ParserConfig",
    "PublicationGateResult", "ReportClaim", "TesseractCliOCR",
    "assess_corpus_quality", "parse_pdf_document", "validate_publication_citations",
    "CONSENSUS_SCHEMA_VERSION", "BrokerEstimate", "ConsensusPoint",
    "ConsensusRevision", "ConsensusSnapshot", "EstimateQuarantine",
    "build_consensus_snapshot", "compare_consensus_snapshots",
    "estimates_from_catalog_outcomes", "normalize_broker_estimate",
    "THS_FORECAST_SOURCE", "ProviderConsensusReference", "ThsForecastAdapter",
    "build_ths_forecast_runtime", "reconcile_ths_broker_estimates",
    "ths_consensus_references",
    "INTELLIGENCE_SCHEMA_VERSION", "SUPPORTED_SOURCE_TYPES",
    "AShareEntityResolver", "CoverageGap", "EntityResolution",
    "InferenceEnvelope", "IntelCollectorAdapter", "IntelSourceSpec",
    "IntelligenceBatch", "IntelligenceEvent", "IntelligenceEvidence",
    "attach_event_inference", "build_event_topology", "canonical_article_url",
    "collect_intelligence", "collect_intelligence_async",
    "EASTMONEY_SELL_SIDE_CATALOG_SOURCE", "EASTMONEY_SELL_SIDE_PDF_SOURCE",
    "EastmoneySellSideCatalogAdapter", "EastmoneySellSidePdfAdapter",
    "RateLimitedRetryTransport", "RetryableHttpError", "SellSideArchiveBatch",
    "SellSideArchiveItem", "build_sell_side_runtime", "sync_sell_side_archive",
    "sync_sell_side_archive_async",
]
